version: '2'

services:
   nginx:
      build: ./docker/nginx
      ports:
         - "5000:80"
      links:
         - fpm:pe
   fpm:
      build:
         context: .
         dockerfile: Dockerfile-Github-Oauth
         args:
            GITHUB_OAUTH: 3c19ddcbed76b70c4d17d670a134bc3f99bbd524
      volumes:
         - ./web:/app/web
        